# Client-side of the application
db:
  image: postgres:9.4
apiserver:
  build: api-server
  volumes:
    - ./api-server:/myapp
emberapp:
  build: ember-application
  command: ember server
  ports:
    - "4200:4200"
    - "49152:49152"
    - "7357:7357"
  volumes:
    - ./ember-application:/myapp
